### PR TITLE
Update Runtime to 21.08

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
bot, build

**Comment by Unrud** [comment]
[org.freedesktop.Sdk.Extension.mono6](https://github.com/flathub/org.freedesktop.Sdk.Extension.mono6) is not available for 21.08.

**Comment by Unrud** [comment]
bot, build

**Comment by Unrud** [comment]
Switching to runtime 21.08 causes problems with Intel graphics (Mesa?). The game hangs on start. It works fine with proprietary nvidia drivers.

**Comment by BryanQuigley** [comment]
Do you remember more specifically what the issue was?

**Comment by Unrud** [comment]
> Do you remember more specifically what the issue was?

It hangs on the following screen:

openra

No error messages are produced.

**Comment by BryanQuigley** [comment]
It looks like the msbuild can also be bumped to https://download.mono-project.com/repo/ubuntu/pool/main/m/msbuild/msbuild_16.10.1+xamarinxplat.2021.05.26.14.00-0xamarin2+debian10b1_all.deb (and maybe others).

Is the test build still somewhere? Did you test off of the old build or make a new one? 
What are your specific Intel card/distro/kernel/etc?

**Comment by Unrud** [comment]
> It looks like the msbuild can also be bumped to

It doesn't compile with the newer version.

> Is the test build still somewhere? Did you test off of the old build or make a new one?

I build a new one myself.

> What are your specific Intel card/distro/kernel/etc?

Tested with Fedora 35 and Ubuntu 20.04. Cards are Intel HD from Haswell and Skylake generations.

**Comment by BryanQuigley** [comment]
bot, build

**Comment by BryanQuigley** [comment]
Was able to reproduce - it's these bugs https://gitlab.freedesktop.org/mesa/mesa/-/issues/4847 | https://github.com/OpenRA/OpenRA/issues/19434

The workaround worked: GALLIUM_THREAD=0 flatpak run net.openra.OpenRA

**Pull request merged**
